webtalk_init -webtalk_dir /home/narayan/Documents/FPGA/new/Exercise_1/Exercise_1.sim/sim_1/behav/xsim/xsim.dir/led_blink_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar 27 20:00:37 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "edd6bf87-e280-462b-80da-2907e148e473" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5e850c251fc4490bae4a5bd2c9be1533" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Pentium(R) CPU B960 @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "859.113 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125332_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2668495075 -regid "" -xml /home/narayan/Documents/FPGA/new/Exercise_1/Exercise_1.sim/sim_1/behav/xsim/xsim.dir/led_blink_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/narayan/Documents/FPGA/new/Exercise_1/Exercise_1.sim/sim_1/behav/xsim/xsim.dir/led_blink_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/narayan/Documents/FPGA/new/Exercise_1/Exercise_1.sim/sim_1/behav/xsim/xsim.dir/led_blink_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
