webtalk_init -webtalk_dir /home/narayan/Documents/FPGA/Exercise_4/Exercise_4.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-04-17 10:11:09" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "tn33tlt48jaofjl9e0bk00diok" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Pentium(R) CPU B960 @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "950.269 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.095 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1555484382000" -context "sdk\\\\bsp/1555484382000"
webtalk_add_data -client sdk -key hwid -value "1555484155000" -context "sdk\\\\bsp/1555484382000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1555484382000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1555484382000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1555484382000"
webtalk_add_data -client sdk -key uid -value "1555484388000" -context "sdk\\\\application/1555484388000"
webtalk_add_data -client sdk -key hwid -value "1555484155000" -context "sdk\\\\application/1555484388000"
webtalk_add_data -client sdk -key bspid -value "1555484382000" -context "sdk\\\\application/1555484388000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1555484388000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1555484388000"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1555484388000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1555484388000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1555484388000"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1555484388000"
webtalk_add_data -client sdk -key projSize -value "303.609375" -context "sdk\\\\application/1555484388000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1555485069601"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1555485069601"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1555485069601"
webtalk_add_data -client sdk -key DebugCount -value "2" -context "sdk\\\\bsp/1555485069601"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1555485069601"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1555485069601"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1555485069601"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1555485069601"
webtalk_transmit -clientid 1750242365 -regid "" -xml /home/narayan/Documents/FPGA/Exercise_4/Exercise_4.sdk/webtalk/usage_statistics_ext_sdk.xml -html /home/narayan/Documents/FPGA/Exercise_4/Exercise_4.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /home/narayan/Documents/FPGA/Exercise_4/Exercise_4.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
