# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/narayan/Documents/FPGA/Exercise_4/Exercise_4.srcs/sources_1/bd/base_zynq/ip/base_zynq_xbar_0/base_zynq_xbar_0.xci
# IP: The module: 'base_zynq_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/narayan/Documents/FPGA/Exercise_4/Exercise_4.srcs/sources_1/bd/base_zynq/ip/base_zynq_xbar_0/base_zynq_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_zynq_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/narayan/Documents/FPGA/Exercise_4/Exercise_4.srcs/sources_1/bd/base_zynq/ip/base_zynq_xbar_0/base_zynq_xbar_0.xci
# IP: The module: 'base_zynq_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/narayan/Documents/FPGA/Exercise_4/Exercise_4.srcs/sources_1/bd/base_zynq/ip/base_zynq_xbar_0/base_zynq_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'base_zynq_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
