# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/narayan/Documents/FPGA/OLED_on_ZedBoard/project_2/project_2.srcs/sources_1/bd/ROM/ip/ROM_blk_mem_gen_0_0/ROM_blk_mem_gen_0_0.xci
# IP: The module: 'ROM_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/narayan/Documents/FPGA/OLED_on_ZedBoard/project_2/project_2.srcs/sources_1/bd/ROM/ip/ROM_blk_mem_gen_0_0/ROM_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/narayan/Documents/FPGA/OLED_on_ZedBoard/project_2/project_2.srcs/sources_1/bd/ROM/ip/ROM_blk_mem_gen_0_0/ROM_blk_mem_gen_0_0.xci
# IP: The module: 'ROM_blk_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/narayan/Documents/FPGA/OLED_on_ZedBoard/project_2/project_2.srcs/sources_1/bd/ROM/ip/ROM_blk_mem_gen_0_0/ROM_blk_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ROM_blk_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
